(function(){'use strict';
const GUIDE={
hourly:{formula:'Jahreskosten = Bruttostundenlohn × Arbeitgeberfaktor × produktive Stunden + Gemeinkosten. Kostensatz = Jahreskosten ÷ produktive Stunden. Verrechnungssatz = Kostensatz × (1 + Gewinnaufschlag).',read:'Der Verrechnungssatz ist die rechnerische Untergrenze für einen kostendeckenden Verkauf je produktiver Stunde. Er ist kein automatisch marktgerechter Preis.',errors:['Anwesenheitsstunden mit produktiven Stunden verwechseln','Gemeinkosten doppelt oder gar nicht berücksichtigen','Gewinnaufschlag mit Marge verwechseln']},
employee:{formula:'Monatliche Arbeitgeberkosten = Monatsbrutto × Arbeitgeberfaktor. Jahreswert = Monatswert × 12.',read:'Der Faktor ist eine transparente Schätzannahme. Für echte Personalkosten können weitere betriebliche Bestandteile hinzukommen.',errors:['Faktor als gesetzlich festen Wert behandeln','Sonderzahlungen und weitere Kosten vergessen','Mitarbeiterkosten direkt mit verrechenbarem Stundensatz gleichsetzen']},
material:{formula:'Material netto = Einkauf × (1 + Verschnitt) × (1 + Aufschlag). Brutto = Netto × (1 + Umsatzsteuer).',read:'Das Ergebnis zeigt einen kalkulatorischen Verkaufspreis auf Basis deiner Annahmen. Verschnitt und Aufschlag wirken nacheinander.',errors:['Verschnitt erst nach dem Aufschlag ergänzen','Aufschlag und Umsatzsteuer verwechseln','Packungs- oder Mindestmengen ignorieren']},
markup:{formula:'Aufschlag % = (Verkauf − Einkauf) ÷ Einkauf × 100. Handelsspanne % = (Verkauf − Einkauf) ÷ Verkauf × 100.',read:'Aufschlag und Handelsspanne beschreiben denselben Preisabstand mit unterschiedlicher Bezugsgröße und sind deshalb nicht identisch.',errors:['Marge und Aufschlag gleichsetzen','Netto- und Bruttopreise mischen','Nebenkosten außerhalb des Einkaufspreises vergessen']},
travel:{formula:'Anfahrtskosten = Strecke × Kosten je km + Fahrzeit × Verrechnungssatz Fahrzeit.',read:'Das Ergebnis trennt Fahrzeug- und Zeitkomponente. Gerade bei längeren Fahrten kann die Zeit den größeren Anteil ausmachen.',errors:['nur einfache Strecke statt Hin- und Rückweg eingeben','Fahrzeit doppelt berechnen','Kilometerwert ohne eigene Kostenbasis übernehmen']},
contribution:{formula:'Deckungsbeitrag = Umsatz − variable Kosten. Deckungsbeitragsquote = Deckungsbeitrag ÷ Umsatz × 100.',read:'Ein positiver Deckungsbeitrag bedeutet noch nicht automatisch Gewinn, weil fixe Kosten anschließend noch gedeckt werden müssen.',errors:['Fixkosten als variable Kosten verbuchen','Brutto-Umsatz mit Netto-Kosten mischen','Deckungsbeitragsquote als Gewinnmarge lesen']},
quote:{formula:'Arbeit = Stunden × Stundensatz. Material = Einkauf × (1 + Aufschlag). Netto = Arbeit + Material + Anfahrt. Brutto = Netto × (1 + Umsatzsteuer).',read:'Die Aufteilung zeigt, welcher Baustein den Angebotspreis treibt und erleichtert spätere Nachkalkulationen.',errors:['Arbeitsstunden zu knapp schätzen','Materialaufschlag und MwSt. vermischen','Nebenleistungen nicht einplanen']},
project:{formula:'Gesamtkosten = Personal + Material + Geräte + Fahrt + Sonstiges. Zielverkauf = Gesamtkosten ÷ (1 − Zielmarge).',read:'Die Zielmarge bezieht sich auf den Verkaufspreis. Deshalb wird sie mathematisch anders behandelt als ein einfacher Kostenaufschlag.',errors:['Marge als Aufschlag rechnen','Kostenpositionen doppelt erfassen','unvorhergesehene Projektkosten ohne Reserve lassen']},
measure:{formula:'Fläche = Länge × Breite × Anzahl.',read:'Das Ergebnis ist eine geometrische Teilfläche. Bei komplexen Grundrissen sollten mehrere Positionen einzeln gerechnet und anschließend addiert werden.',errors:['cm und m mischen','Öffnungen stillschweigend abziehen','unregelmäßige Flächen als Rechteck schätzen']},
timesheet:{formula:'Nettoarbeitszeit = Endzeit − Startzeit − Pause.',read:'Das Ergebnis ist die Nettozeit eines zusammenhängenden Arbeitsblocks. Mehrere Blöcke oder Sonderregeln müssen separat betrachtet werden.',errors:['Pause nicht abziehen','Arbeit über Mitternacht wie einen normalen Tagesblock rechnen','Fahrt- und Arbeitszeit unklar vermischen']},
tiles:{formula:'Bestellfläche = Nettofläche × (1 + Reserve). Stückzahl = Bestellfläche ÷ Fläche einer Fliese.',read:'Die Stückzahl ist rechnerisch. Für den Einkauf muss auf ganze Fliesen und anschließend auf ganze Packungen aufgerundet werden.',errors:['Fliesenmaß in cm nicht in m umrechnen','Reserve pauschal wählen','Packungsinhalt und Charge nicht prüfen']},
waste:{formula:'Bestellfläche = Nettofläche × (1 + Reserve in %).',read:'Die Reserve ist eine Planungsannahme und hängt von Raumform, Verlegebild und Zuschnitten ab.',errors:['10 % als universell ansehen','Ersatzfliesen mit Verschnitt verwechseln','Nischen und diagonale Verlegung unterschätzen']},
paint:{formula:'Literbedarf = Fläche × Anzahl Anstriche ÷ Ergiebigkeit in m²/L.',read:'Der Rechenwert ist nur so gut wie die Ergiebigkeitsangabe. Untergrund und Verarbeitung können den realen Verbrauch deutlich verändern.',errors:['Ergiebigkeit schätzen statt vom Produkt übernehmen','zweiten Anstrich vergessen','nicht auf verfügbare Gebinde aufrunden']},
walls:{formula:'Brutto-Wandfläche = 2 × (Länge + Breite) × Raumhöhe. Nettofläche = Bruttofläche − Öffnungen.',read:'Die Nettofläche ist sinnvoll, wenn der nächste Arbeitsschritt tatsächlich nach m² kalkuliert wird.',errors:['Bodenfläche statt Raumumfang verwenden','Fenster und Türen doppelt abziehen','Schrägen oder Nischen nicht separat rechnen']},
concrete:{formula:'Volumen = Länge × Breite × Höhe. Planmenge = Volumen × (1 + Reserve).',read:'Das Ergebnis ist die geometrische Menge eines rechteckigen Bauteils plus frei gewählte Reserve.',errors:['Dicke in cm statt m einsetzen','komplexe Körper nicht zerlegen','Bestell- und Mindestmengen des Lieferanten ignorieren']},
screed:{formula:'Volumen = Fläche × Schichtdicke in Metern. Masse ≈ Volumen × eingegebene Dichte.',read:'Die Masse ist nur eine Schätzung über die Dichte. Für Sackware ist die konkrete Herstellerergiebigkeit maßgeblich.',errors:['Millimeter nicht in Meter umrechnen','Dichte als universell ansehen','unterschiedliche Schichtdicken nicht berücksichtigen']},
mortar:{formula:'Mörtelvolumen = Fläche × mittlere Schichtdicke in Metern.',read:'Das Ergebnis beschreibt das geometrische Volumen. Reale Verbräuche können durch Untergrund und Verarbeitung abweichen.',errors:['Schichtdicke zu niedrig ansetzen','Unebenheiten ignorieren','Sackbedarf ohne Herstellerergiebigkeit ableiten']},
grout:{formula:'Der Rechner schätzt das Fugenvolumen aus Fläche, Fliesenabmessungen, Fugenbreite und Fugentiefe.',read:'Kleinere Formate erzeugen auf gleicher Fläche mehr Fugenlänge. Der berechnete Wert ist deshalb stark vom Format abhängig.',errors:['Fugenbreite und -tiefe vertauschen','Produktdichte mit Volumen gleichsetzen','Herstellerverbrauch nicht gegenprüfen']},
wallpaper:{formula:'Bahnenzahl ergibt sich aus Raumumfang ÷ Rollenbreite. Bahnlänge = Raumhöhe + Zugabe. Rollenbedarf folgt aus nutzbaren Bahnen pro Rolle.',read:'Bei Mustertapeten kann der Rapport die nutzbare Bahnenzahl pro Rolle reduzieren.',errors:['Rapport ignorieren','Rollenmaße nicht vom Produkt übernehmen','zu knapp ohne Zugabe rechnen']},
roofarea:{formula:'Bei einem einfachen symmetrischen Satteldach: geneigte Dachfläche = horizontale Grundfläche ÷ cos(Dachneigung).',read:'Die Formel gilt nur für einfache Geometrien. Gauben, Kehlen und Überstände müssen als eigene Flächen ergänzt werden.',errors:['schräge statt horizontale Grundfläche einsetzen','Überstände vergessen','Dachfläche direkt als Materialmenge verwenden']},
roofpitch:{formula:'Dachneigung = arctan(Höhenunterschied ÷ horizontale Strecke).',read:'Der Winkel beschreibt die geometrische Neigung. Er sagt allein nichts über zulässige Deckung oder konstruktive Vorgaben aus.',errors:['Sparrenlänge als horizontale Strecke verwenden','Grad und Prozent gleichsetzen','Messpunkte nicht sauber horizontal/vertikal erfassen']},
decking:{formula:'Laufmeterbedarf wird aus Terrassenfläche und wirksamer Deckbreite aus Diele plus Fuge abgeleitet; anschließend wird die Reserve berücksichtigt.',read:'Der Laufmeterwert ist eine Mengenbasis. Stückzahl und Zuschnitt hängen zusätzlich von den verfügbaren Dielenlängen ab.',errors:['Fugenbreite vergessen','Verlegerichtung erst nach der Mengenplanung festlegen','Unterkonstruktion mit Dielenmenge verwechseln']},
doc:{formula:'Dokumentgenerator: Projekt, Datum und Beschreibung bilden die Basis. Ergänze Sachverhalte so konkret, dass eine dritte Person Ort, Leistung und offenen Punkt nachvollziehen kann.',read:'Die Ausgabe ist eine strukturierte Dokumentationshilfe, keine automatische rechtliche oder vertragliche Bewertung.',errors:['pauschale Formulierungen ohne Ort oder Menge','Fristen und Verantwortliche fehlen lassen','rechtliche Wirkung aus dem Generator ableiten']}
};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function apply(){const slug=location.hash.startsWith('#tool/')?location.hash.slice(6):'';if(!slug)return;const t=(window.TOOLS||typeof TOOLS!=='undefined'&&TOOLS||[]).find(x=>x.slug===slug);if(!t)return;const g=GUIDE[t.kind]||GUIDE.doc;const app=document.getElementById('app');if(!app||app.querySelector('.wr-depth-v4'))return;const anchor=app.querySelector('.wr-depth-v3')||app.querySelector('.tool-box');if(!anchor)return;const s=document.createElement('section');s.className='section wr-depth-v4';s.innerHTML=`<div class="content-box"><span class="section-kicker">Rechenweg & Einordnung</span><h2>So entsteht das Ergebnis</h2><h3>Formel bzw. Logik</h3><p>${esc(g.formula)}</p><h3>So liest du das Ergebnis richtig</h3><p>${esc(g.read)}</p><h3>Typische Fehler vermeiden</h3><ul>${g.errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="muted"><strong>Praxis-Tipp:</strong> Ändere bei Unsicherheit immer nur eine Eingabe und beobachte, wie stark sich das Ergebnis verändert. So erkennst du schnell, welche Annahme für dein Projekt den größten Einfluss hat.</p></div>`;anchor.insertAdjacentElement('afterend',s)}
function schedule(){setTimeout(apply,100);setTimeout(apply,300)}
addEventListener('hashchange',schedule);addEventListener('DOMContentLoaded',schedule);const target=document.getElementById('app');if(target)new MutationObserver(schedule).observe(target,{childList:true,subtree:false});schedule();
})();