window.WR_PAGES=window.WR_PAGES||{};
const WR_TOOL_INSIGHTS={
'abnahmeprotokoll-generator':'Halte Zustand, Restarbeiten und Mängel möglichst konkret mit Ort und Zuständigkeit fest. Bei rechtlich relevanten Abnahmen können Vertragslage, Form und Vertretungsberechtigung zusätzliche Anforderungen erzeugen.',
'anfahrtskosten-rechner':'Trenne Fahrzeugkosten und bezahlte Fahrzeit. Gerade bei längeren Strecken kann die Zeit wirtschaftlich stärker ins Gewicht fallen als der reine Kilometerwert.',
'angebotskalkulator':'Ein Angebot wird nachvollziehbarer, wenn Arbeitszeit, Material, Anfahrt und Umsatzsteuer getrennt sichtbar bleiben. Vergleiche nach Projektende Plan- und Istwerte.',
'aufmass-rechner':'Zerlege unregelmäßige Flächen in einfache Teilflächen und dokumentiere Öffnungen oder Abzüge separat. So bleibt der Rechenweg später kontrollierbar.',
'baustellenbericht-generator':'Nenne nicht nur Tätigkeiten, sondern auch konkrete Bereiche, Personal und offene Punkte. Dadurch lässt sich der Bericht später mit Aufmaß, Rapport oder Mängelliste verbinden.',
'bautagesbericht-generator':'Ein Tagesbericht gewinnt durch konkrete Orte, Mengen, Personal, Wetter, Lieferungen und Behinderungen. Zeitnahe Dokumentation ist meist belastbarer als eine spätere Rekonstruktion.',
'betonrechner':'Die Geometrie liefert die Grundmenge. Schalungstoleranzen, Untergrund, Restmengen und Lieferbedingungen können eine zusätzliche Reserve erforderlich machen.',
'dachflaechen-rechner':'Gauben, Kehlen, Überstände oder asymmetrische Dachflächen müssen als eigene Teilflächen berücksichtigt werden. Die geometrische Fläche ist erst der Anfang der Materialplanung.',
'dachneigungs-rechner':'Die waagerechte Strecke muss wirklich horizontal gemessen werden. Die Dachneigung allein entscheidet noch nicht über zulässige Deckung oder konstruktive Anforderungen.',
'deckungsbeitrag-rechner':'Deckungsbeitrag ist nicht gleich Gewinn. Er zeigt, welcher Betrag nach variablen Kosten zur Deckung fixer Kosten und anschließend für Gewinn verbleibt.',
'estrichrechner':'Die Massenabschätzung hängt von der eingegebenen Dichte ab. Für Sackware sollte die Herstellerergiebigkeit die endgültige Bestellgrundlage bilden.',
'farbverbrauch-rechner':'Ergiebigkeit, Untergrund und Anzahl der Anstriche beeinflussen den Bedarf stark. Nutze die technische Angabe des konkreten Produkts statt eines pauschalen Literwerts.',
'fliesen-verschnitt-rechner':'Verschnitt ist projektabhängig. Diagonale Verlegung, Nischen oder viele Anschlüsse benötigen häufig mehr Reserve als eine einfache rechteckige Fläche.',
'fliesenrechner':'Trenne Nettofläche, Reserve, Stückzahl und Packungsmenge. Die errechnete Stückzahl muss für die Bestellung noch mit dem tatsächlichen Packungsinhalt abgeglichen werden.',
'fugenmasse-rechner':'Kleine Fliesen erzeugen auf derselben Fläche mehr Fugenlänge als große Formate. Für die Bestellung hat die Verbrauchsangabe des konkreten Fugenmörtels Vorrang.',
'maengelprotokoll-generator':'Ort, Bauteil, Zustand und gewünschte Nachbesserung sollten so konkret sein, dass eine andere Person den Mangel ohne Rückfrage wiederfindet.',
'materialaufschlag-rechner':'Aufschlag und Marge haben unterschiedliche Bezugsgrößen. Zusätzliche Beschaffungs-, Lager- oder Verschnittkosten gehören gegebenenfalls bereits in die Kostenbasis.',
'materialkosten-rechner':'Trenne Einkauf, Verschnitt, Aufschlag, Netto- und Bruttopreis. So bleibt sichtbar, an welcher Stelle sich eine Preisannahme verändert.',
'mitarbeiterkosten-rechner':'Das Monatsbrutto ist nur ein Teil der betrieblichen Personalkosten. Für den späteren Verrechnungssatz sind zusätzlich produktive Stunden und Gemeinkosten entscheidend.',
'moertelrechner':'Eine mittlere Schichtdicke ist nur eine Annahme. Unebene Untergründe können den realen Bedarf erhöhen; für Sackware ist die Herstellerergiebigkeit entscheidend.',
'projektkosten-rechner':'Trenne Personal, Material, Geräte, Fahrt und sonstige Kosten. Die Zielmarge wird auf den Verkaufspreis bezogen und ist nicht dasselbe wie ein Kostenaufschlag.',
'rapportzettel-generator':'Beschreibe Ort, Tätigkeit, Stunden und Material konkret. Pauschale Angaben wie „diverse Arbeiten“ sind bei späteren Rückfragen wenig hilfreich.',
'regiebericht-generator':'Bei Regiearbeiten sollten Mitarbeiter, Stunden, Leistung und Material nachvollziehbar zusammenpassen. Vertragliche Nachweis- oder Unterschriftsanforderungen sind separat zu prüfen.',
'stundenverrechnungssatz-rechner':'Produktive Stunden sind der kritische Nenner: Urlaub, Krankheit, Organisation und interne Tätigkeiten reduzieren die tatsächlich verrechenbare Zeit.',
'stundenzettel-rechner':'Beginn, Ende und Pausen ergeben eine einfache Nettoarbeitszeit. Mehrere Arbeitsblöcke, Fahrtzeiten oder arbeitsrechtliche Vorgaben benötigen gegebenenfalls eine detailliertere Erfassung.',
'tapetenrechner':'Bei Mustertapeten kann der Rapport zusätzliche Bahnlänge verursachen. Der Grundrechner sollte deshalb mit den konkreten Produktangaben abgeglichen werden.',
'terrassenmaterial-rechner':'Die Fläche wird in Dielen-Laufmeter übersetzt. Danach müssen verfügbare Standardlängen, Verlegerichtung, Zuschnitt und Unterkonstruktion separat geplant werden.',
'wandflaechen-rechner':'Ziehe Fenster und Türen nur dann ab, wenn du für den nächsten Arbeitsschritt tatsächlich die Nettofläche brauchst. Für Farbe oder Tapete können unterschiedliche praktische Zuschläge sinnvoll sein.'
};
const WR_CAT_COPY={
'Betrieb & Kalkulation':['Für Betriebe ist ein Rechner dann hilfreich, wenn Kostenbestandteile sichtbar bleiben. Ändere Annahmen einzeln und prüfe, welcher Wert das Ergebnis wirklich treibt.','Vergleiche das Ergebnis nach dem Auftrag mit Ist-Daten. So wird aus einer einmaligen Berechnung eine bessere Grundlage für spätere Kalkulationen.'],
'Material & Mengen':['Mengenrechner liefern eine mathematische Ausgangsbasis. Für die Bestellung müssen Gebinde, Packungen, Liefermengen und Herstellerangaben zusätzlich berücksichtigt werden.','Prüfe besonders Einheiten, Reserve und Verschnitt. Viele Fehlmengen entstehen nicht in der Formel, sondern bei der Übertragung von Maßen oder Produktdaten.'],
'Baustelle':['Auf der Baustelle zählt eine schnelle, klare Eingabe. Teile komplexe Flächen oder Sachverhalte in nachvollziehbare Einzelpositionen und dokumentiere Besonderheiten direkt.','Wenn Maße oder Berichte später für Abrechnung oder Nachweis wichtig werden, sollten die zugrunde liegenden Angaben zusätzlich projektspezifisch gesichert werden.'],
'Dokumentation':['Dokumentation wird wertvoll, wenn sie konkret ist: Projekt, Datum, Ort, Tätigkeit, Zeit und Material gehören möglichst eindeutig zusammen.','Der Generator hilft bei der Struktur. Vertraglich vorgeschriebene Form, Fristen, Unterschriften oder Rechtswirkungen müssen für den konkreten Auftrag separat geprüft werden.'],
'Renovierung':['Für Renovierungsprojekte sind Produktangaben besonders wichtig. Ergiebigkeit, Rapport, Gebindegröße oder Standardlänge können aus einer mathematischen Menge eine andere reale Einkaufsmenge machen.','Nutze den Rechner zum Planen und kontrolliere das Ergebnis anschließend gegen die Verpackungs- oder Herstellerangaben des gewählten Produkts.']
};
function wrCloseMenu(){const h=document.querySelector('.site-header'),b=document.querySelector('.menu-btn');h?.classList.remove('open');document.body.classList.remove('menu-open');if(b){b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Menü öffnen');b.textContent='☰'}}
function wrInitMenu(){const h=document.querySelector('.site-header'),b=document.querySelector('.menu-btn'),n=document.querySelector('#main-nav');if(!h||!b||!n)return;b.addEventListener('click',e=>{e.stopPropagation();h.classList.contains('open')?wrCloseMenu():(h.classList.add('open'),document.body.classList.add('menu-open'),b.setAttribute('aria-expanded','true'),b.setAttribute('aria-label','Menü schließen'),b.textContent='✕')});n.addEventListener('click',e=>{if(e.target.closest('a'))wrCloseMenu()});document.addEventListener('click',e=>{if(h.classList.contains('open')&&!h.contains(e.target))wrCloseMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')wrCloseMenu()})}
function wrTool(slug){const t=TOOLS.find(x=>x.slug===slug);if(!t){all();return}const rel=TOOLS.filter(x=>x.slug!==slug&&x.cat===t.cat).slice(0,4),cat=WR_CAT_COPY[t.cat]||['Prüfe Eingaben und Einheiten sorgfältig.','Nutze externe Fach- und Herstellerangaben, wenn sie für dein Projekt gelten.'];app.innerHTML=`<div class="breadcrumbs"><a href="#tools">Tools</a> / ${t.title}</div><span class="pill">${t.cat}</span><div class="tool-header"><h1>${t.title}</h1><p class="lead">${t.desc}</p><p class="tool-value-intro">${WR_TOOL_INSIGHTS[slug]||'Nutze das Ergebnis als nachvollziehbare Ausgangsbasis und prüfe die Bedingungen deines konkreten Projekts.'}</p></div><section class="tool-box"><h2>Jetzt ${t.kind==='doc'?'erstellen':'berechnen'}</h2><div class="form-grid">${fields(t.kind)}</div><div class="btn-row"><button class="btn" id="go">Berechnen / Vorschau</button><button class="btn secondary" onclick="window.print()">Drucken / PDF</button></div><div class="result-card" id="result" hidden></div></section><section class="section"><div class="content-box"><span class="section-kicker">Praxis</span><h2>So nutzt du ${t.title.replace(/-Generator|-Rechner/g,'')} sinnvoll</h2><p>${cat[0]}</p><p>${cat[1]}</p><h3>Was das Tool bewusst nicht entscheidet</h3><p>Der Rechner kennt weder deinen vollständigen Vertrag noch jedes konkrete Produkt, jede Norm oder jede Baustellensituation. Wo solche Angaben relevant sind, haben die aktuellen projektspezifischen Unterlagen Vorrang.</p></div></section><section class="section"><h2>Passende nächste Schritte</h2><div class="grid">${rel.map(x=>`<a class="card" href="#tool/${x.slug}"><h3>${x.title}</h3><p class="muted">${x.desc}</p><strong>Weiterarbeiten →</strong></a>`).join('')}</div></section><section class="section faq"><h2>Häufige Fragen</h2><details><summary>Ist das Tool kostenlos?</summary><p>Ja. Die Kernfunktion ist ohne Benutzerkonto nutzbar.</p></details><details><summary>Werden meine Rechenwerte automatisch gespeichert?</summary><p>Nein. Die Berechnung läuft im Browser. Eine lokale Favoritenfunktion wird nur auf ausdrückliche Aktion gespeichert.</p></details><details><summary>Ist das Ergebnis verbindlich?</summary><p>Nein. Es ist eine Rechen- oder Strukturhilfe. Herstellerdaten, Verträge, Normen und individuelle Fachvorgaben können für den Einzelfall entscheidend sein.</p></details></section>`;document.getElementById('go').onclick=()=>calc(t.kind)}
function wrRoute(){const h=location.hash.slice(1)||'home';if(h==='tools')all();else if(h.startsWith('tool/'))wrTool(h.slice(5));else app.innerHTML=WR_PAGES[h]||WR_PAGES.home;wrCloseMenu();scrollTo(0,0)}
addEventListener('hashchange',wrRoute);wrInitMenu();wrRoute();