(function(){
'use strict';
let sheet=null;
const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(/Macintosh/.test(navigator.userAgent)&&navigator.maxTouchPoints>1);
const isAndroid=/Android/i.test(navigator.userAgent);
const isMac=/Mac/i.test(navigator.platform||navigator.userAgent);
function instructions(){if(isIOS)return 'Tippe unten im Browser auf Teilen und wähle „Zum Home-Bildschirm“. Alternativ kannst du die Seite als Favorit sichern.';if(isAndroid)return 'Öffne das Browser-Menü (⋮) und wähle „Zum Startbildschirm hinzufügen“ oder „Lesezeichen“. Danach liegt WerkRechner direkt bei deinen Apps bzw. Favoriten.';return `Drücke ${isMac?'⌘ + D':'Strg + D'}, um WerkRechner als Lesezeichen zu speichern.`}
function ensureSheet(){if(sheet)return sheet;sheet=document.createElement('aside');sheet.className='wr-save-sheet';sheet.setAttribute('aria-live','polite');sheet.innerHTML=`<div class="wr-save-sheet-head"><div><span class="section-kicker">Schneller wiederfinden</span><h3>WerkRechner merken</h3><p>Wenn du die Rechner öfter auf Baustelle oder im Büro brauchst, leg dir die Seite direkt ab.</p></div><button class="wr-save-sheet-close" type="button" aria-label="Schließen">×</button></div><div class="wr-save-steps">${instructions()}</div><div class="btn-row"><button class="btn" type="button" data-wr-copy>Link kopieren</button><button class="btn secondary" type="button" data-wr-share>Teilen</button></div>`;document.body.appendChild(sheet);sheet.querySelector('.wr-save-sheet-close').onclick=closeSheet;sheet.querySelector('[data-wr-copy]').onclick=async e=>{try{await navigator.clipboard.writeText(location.href);e.currentTarget.textContent='Link kopiert ✓';setTimeout(()=>e.currentTarget.textContent='Link kopieren',1600)}catch{}};sheet.querySelector('[data-wr-share]').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'WerkRechner',text:'Kostenlose Rechner und Baustellen-Tools',url:location.href})}catch{}}else{try{await navigator.clipboard.writeText(location.href)}catch{}}};return sheet}
function openSheet(){ensureSheet().classList.add('open')}
function closeSheet(){sheet?.classList.remove('open')}
function injectStrip(){const home=location.hash===''||location.hash==='#home';if(!home)return;const root=document.querySelector('#app');if(!root||root.querySelector('.wr-return-strip'))return;const target=root.querySelector('.wr-command')||root.querySelector('.trust-strip')||root.querySelector('.hero');if(!target)return;const strip=document.createElement('section');strip.className='wr-return-strip';strip.innerHTML=`<div><strong>WerkRechner öfter zur Hand?</strong><p>Speichere dir die Seite einmal ab. Dann bist du beim nächsten Aufmaß, Angebot oder Baustellenbericht mit einem Tipp wieder hier.</p></div><div class="wr-return-actions"><button class="btn" type="button" data-wr-save>WerkRechner merken</button><button class="wr-save-link" type="button" data-wr-share-inline>Link teilen</button></div>`;target.insertAdjacentElement('afterend',strip);strip.querySelector('[data-wr-save]').onclick=openSheet;strip.querySelector('[data-wr-share-inline]').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'WerkRechner',text:'Kostenlose Rechner und Baustellen-Tools',url:location.href})}catch{}}else openSheet()}}
function injectResultReturn(){const r=document.querySelector('#result:not([hidden])');if(!r||r.querySelector('.wr-result-return'))return;const box=document.createElement('div');box.className='wr-result-return';box.innerHTML=`<span>Brauchst du diesen Rechner öfter? Speichere WerkRechner direkt auf deinem Gerät.</span><button type="button">WerkRechner merken</button>`;r.appendChild(box);box.querySelector('button').onclick=openSheet}
function refresh(){setTimeout(()=>{injectStrip();injectResultReturn()},80)}
addEventListener('hashchange',refresh);document.addEventListener('wr:calculated',injectResultReturn);setTimeout(injectStrip,600);
})();