(function(){
  'use strict';
  const FAV_KEY='wr_favorites_v1', RECENT_KEY='wr_recent_v1', TRANSFER_KEY='wr_transfer_v1';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const getJSON=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
  const setJSON=(key,val)=>{try{localStorage.setItem(key,JSON.stringify(val))}catch{}};
  const toolBySlug=slug=>window.TOOLS?.find?.(t=>t.slug===slug)||TOOLS.find(t=>t.slug===slug);
  const currentSlug=()=>{const h=location.hash.slice(1);return h.startsWith('tool/')?h.slice(5):null};
  const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const icons={
    'Betrieb & Kalkulation':'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 7h8M8 11h2M14 11h2M8 15h2M14 15h2"/></svg>',
    'Material & Mengen':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m4.5 7.8 7.5 4.3 7.5-4.3M12 12v9"/></svg>',
    'Baustelle':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20 20 4M7 4h13v13"/><path d="M8 16h2M11 13h2M14 10h2"/></svg>',
    'Dokumentation':'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4.5V3h6v1.5M8 9h8M8 13h8M8 17h5"/></svg>',
    'Renovierung':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 18h10M6 14l8-8 4 4-8 8H6v-4Z"/><path d="m13 7 4 4"/></svg>'
  };
  const catIcon=cat=>`<span class="wr-icon">${icons[cat]||icons['Betrieb & Kalkulation']}</span>`;
  const workflows=[
    {id:'angebot',label:'Angebot kalkulieren',steps:['mitarbeiterkosten-rechner','stundenverrechnungssatz-rechner','materialkosten-rechner','angebotskalkulator','deckungsbeitrag-rechner']},
    {id:'fliesen',label:'Fliesenprojekt',steps:['aufmass-rechner','fliesenrechner','fliesen-verschnitt-rechner','fugenmasse-rechner','materialkosten-rechner']},
    {id:'renovierung',label:'Renovierung planen',steps:['wandflaechen-rechner','farbverbrauch-rechner','materialkosten-rechner','projektkosten-rechner']},
    {id:'doku',label:'Baustelle dokumentieren',steps:['bautagesbericht-generator','rapportzettel-generator','aufmass-rechner','abnahmeprotokoll-generator','maengelprotokoll-generator']}
  ];
  function rememberRecent(slug){if(!slug)return;let list=getJSON(RECENT_KEY,[]).filter(x=>x!==slug);list.unshift(slug);setJSON(RECENT_KEY,list.slice(0,6))}
  function isFav(slug){return getJSON(FAV_KEY,[]).includes(slug)}
  function toggleFav(slug){let l=getJSON(FAV_KEY,[]);l=l.includes(slug)?l.filter(x=>x!==slug):[slug,...l].slice(0,12);setJSON(FAV_KEY,l);return l.includes(slug)}
  function toolCard(t,compact=false){return `<a class="wr-tool-card${compact?' compact':''}" href="#tool/${esc(t.slug)}">${catIcon(t.cat)}<span class="wr-tool-card-copy"><small>${esc(t.cat)}</small><strong>${esc(t.title)}</strong>${compact?'':`<span>${esc(t.desc)}</span>`}</span><span class="wr-arrow">→</span></a>`}
  function searchTools(q){const term=(q||'').trim().toLocaleLowerCase('de');if(!term)return TOOLS.slice(0,8);return TOOLS.filter(t=>(t.title+' '+t.desc+' '+t.cat).toLocaleLowerCase('de').includes(term)).slice(0,10)}
  function bindSearch(root){const input=$('[data-wr-search]',root),results=$('[data-wr-search-results]',root);if(!input||!results)return;const render=()=>{const found=searchTools(input.value);results.innerHTML=found.length?found.map(t=>toolCard(t,true)).join(''):'<div class="wr-search-empty">Kein passendes Tool gefunden. Versuch einen Begriff wie „Fliesen“, „Stundensatz“, „Rapport“ oder „Farbe“.</div>'};input.addEventListener('input',render);input.addEventListener('focus',render);render()}
  function injectTopSearch(){const main=$('#app');if(!main||$('.wr-command',main))return;const isHome=(location.hash===''||location.hash==='#home'),isTools=location.hash==='#tools';if(!isHome&&!isTools)return;const anchor=isHome?$('.hero',main):main.firstElementChild;const box=document.createElement('section');box.className='wr-command';box.innerHTML=`<div class="wr-command-head"><div><span class="section-kicker">Schnell finden</span><h2>Was möchtest du erledigen?</h2><p>Tippe deine Aufgabe ein – WerkRechner zeigt direkt die passenden Werkzeuge.</p></div><span class="wr-shortcut">28 Tools</span></div><div class="wr-searchbox"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m16.5 16.5 4 4"/></svg><input data-wr-search autocomplete="off" inputmode="search" placeholder="z. B. Stundensatz, Fliesen, Beton, Rapport …" aria-label="WerkRechner durchsuchen"></div><div class="wr-search-results" data-wr-search-results></div>`;if(isHome&&anchor)anchor.insertAdjacentElement('afterend',box);else main.insertBefore(box,main.children[1]||null);bindSearch(box);injectPersonalTools(box)}
  function injectPersonalTools(after){const favs=getJSON(FAV_KEY,[]).map(toolBySlug).filter(Boolean),recent=getJSON(RECENT_KEY,[]).map(toolBySlug).filter(Boolean);if(!favs.length&&!recent.length)return;const sec=document.createElement('section');sec.className='wr-personal';sec.innerHTML=`${favs.length?`<div><div class="wr-mini-head"><strong>★ Meine Werkzeuge</strong><button type="button" data-open-favs>Alle anzeigen</button></div><div class="wr-personal-row">${favs.slice(0,4).map(t=>toolCard(t,true)).join('')}</div></div>`:''}${recent.length?`<div><div class="wr-mini-head"><strong>Zuletzt verwendet</strong></div><div class="wr-personal-row">${recent.slice(0,4).map(t=>toolCard(t,true)).join('')}</div></div>`:''}`;after.insertAdjacentElement('afterend',sec);$('[data-open-favs]',sec)?.addEventListener('click',openFavorites)}
  function enhanceCards(){$$('.card[href^="#tool/"]').forEach(card=>{if($('.wr-icon',card))return;const slug=card.getAttribute('href').split('/').pop(),t=toolBySlug(slug);if(!t)return;card.classList.add('wr-enhanced-card');card.insertAdjacentHTML('afterbegin',catIcon(t.cat))})}
  function workflowFor(slug){return workflows.find(w=>w.steps.includes(slug))}
  function injectWorkflow(slug){const box=$('.tool-box');if(!box||$('.wr-workflow-progress'))return;const w=workflowFor(slug);if(!w)return;const idx=w.steps.indexOf(slug);const nav=document.createElement('nav');nav.className='wr-workflow-progress';nav.setAttribute('aria-label','Arbeitsablauf');nav.innerHTML=`<div class="wr-workflow-title"><span>${esc(w.label)}</span><strong>Schritt ${idx+1} von ${w.steps.length}</strong></div><div class="wr-step-track">${w.steps.map((s,i)=>{const t=toolBySlug(s);return `<a href="#tool/${s}" class="${i<idx?'done':i===idx?'active':''}" title="${esc(t?.title||s)}"><span>${i<idx?'✓':i+1}</span><em>${esc((t?.title||s).replace(/-Rechner|-Generator/g,''))}</em></a>`}).join('')}</div>`;box.insertAdjacentElement('beforebegin',nav)}
  const presets={'fliesenrechner':[['5 % Reserve',{waste:5}],['10 % Reserve',{waste:10}],['15 % Reserve',{waste:15}]],'fliesen-verschnitt-rechner':[['5 % Reserve',{waste:5}],['10 % Reserve',{waste:10}],['15 % Reserve',{waste:15}]],'betonrechner':[['0 % Reserve',{reserve:0}],['5 % Reserve',{reserve:5}],['10 % Reserve',{reserve:10}]],'farbverbrauch-rechner':[['6 m²/L',{coverage:6}],['8 m²/L',{coverage:8}],['10 m²/L',{coverage:10}]],'stundenverrechnungssatz-rechner':[['1.200 h',{productive:1200}],['1.350 h',{productive:1350}],['1.500 h',{productive:1500}]]};
  function injectPresets(slug){const list=presets[slug];if(!list||$('.wr-presets'))return;const grid=$('.form-grid');if(!grid)return;const wrap=document.createElement('div');wrap.className='wr-presets';wrap.innerHTML=`<span>Schnellwerte <small>– nur Szenarien, frei anpassbar</small></span>${list.map((p,i)=>`<button type="button" data-preset="${i}">${esc(p[0])}</button>`).join('')}`;grid.insertAdjacentElement('beforebegin',wrap);wrap.addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(!b)return;const data=list[+b.dataset.preset][1];Object.entries(data).forEach(([id,v])=>{const el=document.getElementById(id);if(el){el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))}});$$('button',wrap).forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
  function injectInputHelp(){const help={productive:'Verrechenbare Stunden – nicht einfach Anwesenheitszeit.',factor:'Frei wählbare Annahme für zusätzliche Arbeitgeberkosten.',waste:'Reserve/Verschnitt bewusst an dein Projekt anpassen.',coverage:'Ergiebigkeit des konkreten Produkts verwenden.',margin:'Marge bezieht sich auf den Verkaufspreis.',markup:'Aufschlag bezieht sich auf die Kostenbasis.'};$$('.field').forEach(field=>{const input=$('input,select,textarea',field),label=$('label',field);if(!input||!label||!help[input.id]||$('.wr-help',field))return;const b=document.createElement('button');b.type='button';b.className='wr-help';b.setAttribute('aria-label','Erklärung anzeigen');b.textContent='?';const tip=document.createElement('span');tip.className='wr-help-tip';tip.textContent=help[input.id];label.appendChild(b);field.appendChild(tip);b.addEventListener('click',()=>field.classList.toggle('help-open'))})}
  const zeroOk=new Set(['profit','waste','reserve','openings','travel','other','markup','break','extra']);
  function validateTool(){let bad=null;$$('.tool-box input[type="number"]').forEach(el=>{el.classList.remove('wr-invalid');if(bad)return;const v=parseFloat(el.value);if(!Number.isFinite(v)||(v<0)||(!zeroOk.has(el.id)&&v===0)){el.classList.add('wr-invalid');bad=el}});let msg=$('.wr-form-error');if(!msg){msg=document.createElement('div');msg.className='wr-form-error';$('.tool-box .form-grid')?.insertAdjacentElement('afterend',msg)}if(bad){msg.textContent='Bitte prüfe das markierte Feld. Für diese Berechnung wird ein gültiger Wert benötigt.';bad.focus();return false}msg.textContent='';return true}
  function calcTransfer(slug){const n=id=>parseFloat(document.getElementById(id)?.value)||0;if(slug==='stundenverrechnungssatz-rechner'){const c=n('wage')*n('factor')*n('productive')+n('overhead'),rate=(c/n('productive'))*(1+n('profit')/100);return {target:'angebotskalkulator',label:'Stundensatz ins Angebot übernehmen',values:{rate:+rate.toFixed(2)}}}if(slug==='aufmass-rechner')return {target:'fliesenrechner',label:'Fläche im Fliesenrechner verwenden',values:{area:+(n('length')*n('width')*Math.max(1,n('qty'))).toFixed(2)}};if(slug==='wandflaechen-rechner'){const a=(n('length')+n('width'))*2*n('height')-n('openings');return {target:'farbverbrauch-rechner',label:'Wandfläche für Farbe übernehmen',values:{area:+Math.max(0,a).toFixed(2)}}}if(slug==='fliesenrechner')return {target:'fugenmasse-rechner',label:'Fläche zur Fugenmasse übernehmen',values:{area:n('area')}};if(slug==='materialkosten-rechner')return {target:'angebotskalkulator',label:'Material ins Angebot übernehmen',values:{material:n('buy'),markup:n('markup'),vat:n('vat')}};if(slug==='anfahrtskosten-rechner'){const total=n('km')*n('cpk')+n('time')*n('rate');return {target:'angebotskalkulator',label:'Anfahrt ins Angebot übernehmen',values:{travel:+total.toFixed(2)}}}if(slug==='stundenzettel-rechner'){const a=(document.getElementById('start')?.value||'0:0').split(':'),z=(document.getElementById('end')?.value||'0:0').split(':'),mins=Math.max(0,(+z[0]*60+(+z[1]||0))-(+a[0]*60+(+a[1]||0))-n('break'));return {target:'angebotskalkulator',label:'Arbeitszeit ins Angebot übernehmen',values:{hours:+(mins/60).toFixed(2)}}}if(slug==='dachneigungs-rechner'){const deg=Math.atan2(n('rise'),n('run'))*180/Math.PI;return {target:'dachflaechen-rechner',label:'Dachneigung zur Dachfläche übernehmen',values:{pitch:+deg.toFixed(2)}}}return null}
  function applyIncomingTransfer(slug){let data;try{data=JSON.parse(sessionStorage.getItem(TRANSFER_KEY)||'null')}catch{}if(!data||data.target!==slug)return;Object.entries(data.values||{}).forEach(([id,v])=>{const el=document.getElementById(id);if(el){el.value=v;el.classList.add('wr-prefilled')}});sessionStorage.removeItem(TRANSFER_KEY);const box=$('.tool-box');if(box){const note=document.createElement('div');note.className='wr-transfer-note';note.innerHTML=`<strong>✓ Werte übernommen</strong><span>Aus ${esc(data.fromTitle||'dem vorherigen Tool')}. Du kannst sie vor der Berechnung jederzeit ändern.</span>`;box.insertAdjacentElement('afterbegin',note)}}
  function resultInterpretation(slug){const map={'stundenverrechnungssatz-rechner':'Nutze den Satz als Kalkulationsbasis und vergleiche ihn regelmäßig mit tatsächlich verrechneten Stunden und Ist-Kosten.','fliesenrechner':'Runde für den Einkauf zusätzlich auf ganze Packungen und prüfe Charge, Verlegebild sowie Ersatzbedarf.','betonrechner':'Das geometrische Volumen ist die Basis. Lieferbedingungen und reale Bauteiltoleranzen können die Bestellmenge verändern.','farbverbrauch-rechner':'Vergleiche den Literbedarf mit der Ergiebigkeit und Gebindegröße deiner tatsächlich gewählten Farbe.','angebotskalkulator':'Prüfe neben dem Endpreis auch, ob Arbeitszeit, Material und Anfahrt realistisch angesetzt wurden.','deckungsbeitrag-rechner':'Ein positiver Deckungsbeitrag ist noch kein Gewinn: Fixkosten müssen daraus ebenfalls gedeckt werden.'};return map[slug]||'Prüfe das Ergebnis gegen deine realen Projektwerte und nutze den nächsten sinnvollen Arbeitsschritt.'}
  function enhanceResult(slug){const card=$('.result-card');if(!card||card.hidden)return;const big=$('.result-big',card)?.textContent||'';if($('.wr-result-footer',card))return;const transfer=calcTransfer(slug),footer=document.createElement('div');footer.className='wr-result-footer';footer.innerHTML=`<div class="wr-result-meaning"><span>Einordnung</span><p>${esc(resultInterpretation(slug))}</p></div><div class="wr-result-actions"><button class="btn secondary" type="button" data-copy-result>Ergebnis kopieren</button>${transfer?`<button class="btn" type="button" data-transfer>${esc(transfer.label)} →</button>`:''}</div>`;card.appendChild(footer);$('[data-copy-result]',footer)?.addEventListener('click',async e=>{const txt=`${$('.tool-header h1')?.textContent||'WerkRechner'}: ${big}`;try{await navigator.clipboard.writeText(txt);e.currentTarget.textContent='✓ Kopiert'}catch{e.currentTarget.textContent='Kopieren nicht möglich'}});$('[data-transfer]',footer)?.addEventListener('click',()=>{const t=toolBySlug(slug);sessionStorage.setItem(TRANSFER_KEY,JSON.stringify({...transfer,from:slug,fromTitle:t?.title||slug}));location.hash='tool/'+transfer.target});showMobileResult(big)}
  function showMobileResult(big){let peek=$('.wr-mobile-result');if(!peek){peek=document.createElement('div');peek.className='wr-mobile-result';peek.innerHTML='<div><small>Dein Ergebnis</small><strong></strong></div><button type="button">Ansehen</button>';document.body.appendChild(peek);$('button',peek).addEventListener('click',()=>$('.result-card')?.scrollIntoView({behavior:'smooth',block:'center'}))}$('strong',peek).textContent=big;peek.classList.add('show')}
  function hideMobileResult(){$('.wr-mobile-result')?.classList.remove('show')}
  function enhanceTool(){const slug=currentSlug();if(!slug)return;rememberRecent(slug);hideMobileResult();const t=toolBySlug(slug),head=$('.tool-header');if(head&&!$('.wr-tool-utility')){const row=document.createElement('div');row.className='wr-tool-utility';row.innerHTML=`<div class="wr-trust-row"><span>✓ ohne Anmeldung</span><span>✓ lokal im Browser</span><span>✓ Rechenweg erklärt</span></div><button class="wr-fav-btn ${isFav(slug)?'active':''}" type="button" aria-pressed="${isFav(slug)}">${isFav(slug)?'★ Gespeichert':'☆ Favorit'}</button>`;head.appendChild(row);$('.wr-fav-btn',row).addEventListener('click',e=>{const on=toggleFav(slug);e.currentTarget.classList.toggle('active',on);e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'★ Gespeichert':'☆ Favorit'})}injectWorkflow(slug);injectPresets(slug);injectInputHelp();applyIncomingTransfer(slug);const btn=$('#go');if(btn&&!btn.dataset.uxBound){btn.dataset.uxBound='1';btn.onclick=()=>{if(!validateTool())return;calc(t.kind);enhanceResult(slug)};$$('.tool-box input').forEach(i=>i.addEventListener('input',()=>i.classList.remove('wr-invalid')))}}
  function buildDrawer(){if($('#wr-drawer'))return;const d=document.createElement('div');d.id='wr-drawer';d.className='wr-drawer';d.innerHTML=`<button class="wr-drawer-backdrop" type="button" aria-label="Schließen"></button><section class="wr-drawer-panel" role="dialog" aria-modal="true" aria-label="Werkzeuge suchen"><div class="wr-drawer-head"><div><small>WerkRechner</small><strong data-drawer-title>Tool finden</strong></div><button type="button" data-close-drawer aria-label="Schließen">×</button></div><div data-drawer-content></div></section>`;document.body.appendChild(d);$$('[data-close-drawer],.wr-drawer-backdrop',d).forEach(x=>x.addEventListener('click',closeDrawer))}
  function openSearch(){buildDrawer();const d=$('#wr-drawer'),c=$('[data-drawer-content]',d);$('[data-drawer-title]',d).textContent='Was möchtest du erledigen?';c.innerHTML=`<div class="wr-searchbox large"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m16.5 16.5 4 4"/></svg><input data-wr-search autocomplete="off" inputmode="search" placeholder="Tool oder Aufgabe suchen …" aria-label="WerkRechner durchsuchen"></div><div class="wr-search-results drawer-results" data-wr-search-results></div>`;d.classList.add('open');bindSearch(c);setTimeout(()=>$('[data-wr-search]',c)?.focus(),50)}
  function openFavorites(){buildDrawer();const d=$('#wr-drawer'),c=$('[data-drawer-content]',d),favs=getJSON(FAV_KEY,[]).map(toolBySlug).filter(Boolean),recent=getJSON(RECENT_KEY,[]).map(toolBySlug).filter(Boolean);$('[data-drawer-title]',d).textContent='Meine Werkzeuge';c.innerHTML=`<div class="wr-drawer-section"><h3>Favoriten</h3>${favs.length?favs.map(t=>toolCard(t,true)).join(''):'<p class="muted">Noch keine Favoriten. Öffne einen Rechner und tippe auf „☆ Favorit“.</p>'}</div><div class="wr-drawer-section"><h3>Zuletzt verwendet</h3>${recent.length?recent.map(t=>toolCard(t,true)).join(''):'<p class="muted">Noch kein Rechner verwendet.</p>'}</div>`;d.classList.add('open')}
  function closeDrawer(){$('#wr-drawer')?.classList.remove('open')}
  function injectBottomNav(){if($('.wr-bottom-nav'))return;const nav=document.createElement('nav');nav.className='wr-bottom-nav';nav.setAttribute('aria-label','Mobile Navigation');nav.innerHTML=`<a href="#home"><span>⌂</span><small>Start</small></a><a href="#tools"><span>▦</span><small>Tools</small></a><button type="button" data-bottom-search><span>⌕</span><small>Suche</small></button><button type="button" data-bottom-favs><span>☆</span><small>Favoriten</small></button>`;document.body.appendChild(nav);$('[data-bottom-search]',nav).addEventListener('click',openSearch);$('[data-bottom-favs]',nav).addEventListener('click',openFavorites)}
  function enhanceCurrentView(){hideMobileResult();injectTopSearch();enhanceCards();enhanceTool();$$('[data-clear-preferences]').forEach(b=>{if(b.dataset.uxBound)return;b.dataset.uxBound='1';b.addEventListener('click',()=>{localStorage.removeItem(FAV_KEY);localStorage.removeItem(RECENT_KEY);b.textContent='✓ Lokale Einstellungen gelöscht'})});closeDrawer()}
  window.wrOpenSearch=openSearch;injectBottomNav();buildDrawer();addEventListener('hashchange',()=>requestAnimationFrame(enhanceCurrentView));setTimeout(enhanceCurrentView,0);
})();